/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.whiteboard

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    val hello: Int = 123

}

fun main(args: Array<String>) {
    println(App().greeting + ' ' + App().hello)
    SpringApplication.run(App::class.java, *args)
}
